journal:
  text_module:
    toolbar:
      - 
        - ["Bold", "Italic"]
        - ["Link", "Unlink", "Anchor", "-", "Image"]
        - ["NumberedList", "BulletedList", "Blockquote"]
        - ["Undo", "Redo", "-", "Find"]
      -
        - ["Subscript", "Superscript", "-", "Maximize"]
        - ["Source"]
  externally_managed_images_category: 1

